DROP TABLE JDBCTEST;
CREATE TABLE JDBCTEST(
	NO NUMBER,
	NAME VARCHAR2(100),
	NICKNAME VARCHAR2(200)
);
SELECT * FROM JDBCTEST;

INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');
INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');
INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');
INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');
INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');
INSERT INTO JDBCTEST VALUES(1, '褻⑷遽','獲鍛');